/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/BullyScene.glb -T 
Files: public/models/BullyScene.glb [71.23MB] > C:\Users\Studio\Desktop\GorillaBullys\Web3Webflow\BullyScene-transformed.glb [2.62MB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BullyScene(props) {
  const { nodes, materials } = useGLTF('http://localhost:5173/public/models/BullyScene.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Top_Teeth001.geometry} material={materials['Teeth.001']} position={[0.009, -0.015, 0.044]} scale={0.079} />
      <mesh castShadow receiveShadow  geometry={nodes.Tongue001.geometry} material={materials['Tongue.001']} position={[0.011, -0.015, 0.044]} scale={0.079} />
      <group position={[-0.026, 1.389, 0.267]} scale={0.08}>
      </group>
      <mesh castShadow receiveShadow  geometry={nodes.Bully2.geometry} material={materials['Vampire Bully Base']} position={[0, -0.007, 0]} />
    </group>
  )
}

useGLTF.preload('http://localhost:5173/public/models/BullyScene.glb')
