/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/bully2.glb -T 
Files: public/models/bully2.glb [17.74MB] > C:\Users\Studio\Desktop\GorillaBullys\Web3Webflow\bully2-transformed.glb [603.6KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bully2(props) {
  const { nodes, materials } = useGLTF('http://localhost:5173/public/models/Bully2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bully2.geometry} material={materials['Vampire Bully Base']} position={[0, -0.007, 0]} />
    </group>
  )
}

useGLTF.preload('http://localhost:5173/public/models/Bully2.glb')
