/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Teeth.glb -T 
Files: public/models/Teeth.glb [1.39MB] > C:\Users\Studio\Desktop\GorillaBullys\Web3Webflow\Teeth-transformed.glb [137.43KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Teeth(props) {
  const { nodes, materials } = useGLTF('http://localhost:5173/public/models/Teeth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Tongue001.geometry} material={materials['Material.004']} />
    </group>
  )
}

useGLTF.preload('http://localhost:5173/public/models/Teeth.glb')
